title: Ethan Shapiro # your name (or website title) here
logo: "/images/Ethan_Prof_Pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <p align="center">
  <a href="mailto:enshapir@uci.edu">Email</a> |
  <a href="https://www.linkedin.com/in/ethan-shapiro-dsc/">LinkedIn</a> |
  <a href="https://github.com/Ethan-Shapiro">GitHub</a>
  </p>

  Currently pursuing my Master of Data Science at UC Irvine with a BS in Data Science from UC San Diego. Experienced in the full data science pipeline—from data engineering and big data processing to machine learning and model deployment—gained through internships and academic research.
  <br><br>
  Passionate about leveraging big data and analytics to drive product decisions and understand user behavior. Focused on creating better user experiences through data-driven insights and product development. 
  <br><br>
  <a href="https://www.linkedin.com/in/ethan-shapiro-dsc/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
